;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        coffee-newline-and-indent
        dabbrev-expand
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        py-electric-comment
        python-backspace
        python-electric-colon
        sgml-slash
        skeleton-pair-insert-maybe
        transpose-line-up
        ))

(setq mc/cmds-to-run-once
      '(
        delete-rectangle
        python-send-buffer
        static-kick
        transpose-line-down
        ))
